GLOBAL:
    TIMEZONE: "Europe/Prague"
    LOGFILE: "-"
    PIDFILE: "/tmp/jetconf-resolver.pid"
    PERSISTENT_CHANGES: false
    LOG_LEVEL: "debug"
    LOG_DBG_MODULES: ["usr_conf_data_handlers", "usr_state_data_handlers", "nacm", "data", "usr_action_handlers", "usr_op_handlers"]
    YANG_LIB_DIR: "../yang-modules"
    DATA_JSON_FILE: "example-data-nacm.json"
    BACKEND_PACKAGE: "jetconf_knot"

HTTP_SERVER:
    DBG_DISABLE_CERTS: false
    DOC_ROOT: "doc-root"
    DOC_DEFAULT_NAME: "index.html"
    SERVER_NAME: "jetconf-h2"
    SERVER_SSL_CERT: "server_localhost.crt"
    SERVER_SSL_PRIVKEY: "server_localhost.key"
    CA_CERT: "ca.pem"

NACM:
  ENABLED: false
  ALLOWED_USERS: ["example@mail.cz"]

KNOT:
    LOAD_CONF: false
    SOCKET: "/home/jetconf/knot-conf/knot.sock"
